### ISSUE TITLE
Doesn't work with D8

### ISSUE THREAD

**Issue by sirbralex** [yandex/mapkit-android-demo#32] opened 2018-10-03 09:56 UTC
Build failed with log like
```
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process MyProject\app\build\intermediates\transforms\desugar\debug\10.jar
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by vbazhenov** [comment] 2018-10-03 09:59
Most likely duplicate of #2

**Closed by vbazhenov** 2018-10-03 09:59 UTC
